shop/project/urls.py
from django.contrib import admin
from django.urls import path
from project import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('',views.index,name="index"),
    path('createuser',views.createuser,name="createuser"),
    path("login",views.login,name="login"),
    path("logout",views.logout,name="logout"),
    path('cart',views.cart,name="cart"),
    path('cartdata',views.cartdata,name="cartdata"),
    path("delete",views.deletecart,name="deletecart"),
    path('checkoutSession',views.checkoutSession,name="checkoutSession"),
    path("success",views.success,name="success"),
    path("account",views.account,name="account"),
    path('order',views.order,name="order"),
    path('updateProfile',views.updateProfile,name="updateProfile"),
    path("updateQuantity",views.updateQuantity,name="updateQuantity"),
    path("passwordchange",views.passwordchange,name="passwordchange"),
    path("password_reset",auth_views.PasswordResetView.as_view(template_name="password_reset.html"),name="password_reset"),
    path("password_reset_done",auth_views.PasswordResetDoneView.as_view(template_name="password_reset_done.html"),name="password_reset_done"),
    path("password_reset_confirm/<uidb64>/<token>",auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"),name="password_reset_confirm"),
    path("password_reset_complete",auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"),name="password_reset_complete"),
    path('add_address', views.add_address, name='add_address'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('checkout',views.checkout,name="checkout"),
    path('updateAddress/<int:id>',views.updateAddress,name="updateAddress"),
    path('delete_address/<int:id>',views.delete_address,name="delete_address")
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('project.urls'))
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

shop/project/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Person(models.Model):
    city=models.CharField(max_length=100,null=True,default='')
    date=models.DateTimeField(auto_now_add=True)

class Product(models.Model):
    name=models.CharField(max_length=10)
    price = models.IntegerField()
    image = models.ImageField(upload_to = 'products', default='')

    def __str__(self):
        return self.name

class Cart(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    price = models.FloatField()
    quantity = models.IntegerField()
    userid=models.CharField(max_length=100,default='')


class Country(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name

class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name

class Address(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    address= models.CharField(max_length=200)
    pincode = models.CharField(max_length=6)
    mobile_no = models.CharField(max_length=10)
    user_id=models.IntegerField(default='')
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.first_name
    
class Order(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    price = models.FloatField()
    quantity = models.IntegerField()
    userid = models.IntegerField()
    created_at = models.DateTimeField()
    stripe_payment_intent = models.CharField(max_length=2000)
    email=models.EmailField()
    has_paid = models.BooleanField(default=False)
    status = models.CharField(max_length=10)
    address = models.ForeignKey(Address,on_delete=models.CASCADE,null=True)

shop/project/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from .models import Address,City

class Signupform(UserCreationForm):
    first_name = forms.CharField(max_length=10)
    last_name = forms.CharField(max_length=10)
    email = forms.EmailField()
    password1 = forms.CharField(label='Enter password',widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password',widget=forms.PasswordInput)
    class Meta(UserCreationForm):
        model=User
        fields=['username','first_name','last_name','email','password1','password2']

    def clean_email(self):
      email=self.cleaned_data['email']
      if User.objects.filter(email= email).exists():
        raise forms.ValidationError("Email already exists")
      return email

class MyUserChangeForm(forms.ModelForm):
    password = None
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email')
  

class AddressForm(forms.ModelForm):
    class Meta:
        model=Address
        fields=('first_name','last_name','address','country','city','pincode','mobile_no')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')




 

shop/project/views.py
from ast import Add
from django.shortcuts import redirect, render
from requests import request

from .models import  Address, Product,Cart,City
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate,logout as django_logout, login as auth_login
import stripe
from django.http import JsonResponse
from django.http.response import HttpResponseNotFound
from .forms import AddressForm, Signupform,MyUserChangeForm
from django.conf import settings

from django.core.mail import send_mail
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy

import datetime
from .models import Order
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
stripe.api_key="sk_test_51L2TV5SBnyV9WLBjK9AF2s5bwq0oVhsgdxzIWFpkO1CYbkZqn8ID3JEfWFWyFhbf2ilKqQbpfroEincm8loi31gD00tu2wvisi"
# Create your views here.


def add_address(request):
    if request.method=="POST":
        current_user=request.user
        form=AddressForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            address= form.cleaned_data['address']
            pincode = form.cleaned_data['pincode']
            mobile_no= form.cleaned_data['mobile_no']
            country= form.cleaned_data['country']
            city = form.cleaned_data['city']
            c=Address(first_name=first_name,user_id=current_user.id,last_name=last_name,address=address,mobile_no=mobile_no,country=country,city=city,pincode=pincode)
            c.save()
            
            messages.success(request,'Account created successfully')  
            return redirect('updateProfile')
    else:
        form=AddressForm()
    return render(request,'project/address_form.html',{'form':form})
        


def load_cities(request):   
    country_id = request.GET.get('country')
    cities = City.objects.filter(country_id=country_id).order_by('name')
    return render(request, 'project/city.html', {'cities': cities})

def index(request):
    pro=Product.objects.all()
    return render(request,"index.html",{'pro':pro})

def createuser(request):
    if request.method=="POST":
        form=Signupform(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Account created successfully')  
            return redirect("login")
    else:
        form=Signupform()
    return render(request,"createuser.html",{'form':form})

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username = username, password = password)
        if user is not None:
            form = auth_login(request,user)
            return redirect("index")
        else:
            messages.info(request,'invalid username or password')     
            form = AuthenticationForm()
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form':form})

def logout(request):
   django_logout(request)
   return redirect("login") 


def cart(request):
    if request.user.is_authenticated:
        current_user=request.user
        product_id=request.GET["product_id"]
        item=Cart.objects.filter(product_id=product_id,userid=current_user.id).exists()
        if item!=True:
            obj=Product.objects.filter(id=product_id).values()
            add=Cart(product_id=product_id,price=obj[0]['price'],userid=current_user.id,quantity=1)
            add.save()
            response = {'status': 'success'}
            return JsonResponse(response)
        else:        
           response = {'status': 'failed'}
           return JsonResponse(response)
    else:
        return redirect("login")
         
def cartdata(request):
    if request.user.is_authenticated:
        current_user=request.user
        obj=Cart.objects.select_related('product').filter(userid=current_user.id)
        if len(obj)>0:  
            total = 0
            for a in obj:
                 total = total + (a.quantity * a.price)
            return render(request,"cartdata.html",{'obj':obj,'total':total})
        else:
            return render(request,"empty.html")
    else:
        return redirect("login")

def deletecart(request):
    removecart=request.GET["remove_cart"]

    obj=Cart.objects.filter(id=removecart)
    obj.delete()
    response = {'status': 'success', 'message': 'product has been deleted'}
    return JsonResponse(response)

def passwordchange(request):
    if request.method=="POST":
        user=request.user
        data=request.POST
        obj=PasswordChangeForm(user,data)
        if obj.is_valid():
            obj.save()
            update_session_auth_hash(request,obj.user)
            messages.info(request,'Password Change Successfully')   
    else:
        obj=PasswordChangeForm(user=request.user)
    return render(request,"passwordchange.html",{'password':obj})

def checkout(request):
    current_user = request.user
    show=Address.objects.filter(user_id=current_user.id)
    list =Cart.objects.select_related('product').filter(userid = current_user.id)
    total = 0
    for obj in list:
     total = total + (obj.quantity * obj.price)
    return render(request,"checkout.html",{'checkList':list,'grandtotal':total,'showAddress':show})


def checkoutSession(request):
    current_user = request.user
    addressId=request.GET.get("addressId")
    list =Cart.objects.select_related('product').filter(userid = current_user.id)
    obj = list[0]   
    YOUR_DOMAIN = "http://127.0.0.1:8000"
    checkout_session = stripe.checkout.Session.create(
            
            payment_method_types=['card'],
            line_items=[
                {
                    'price_data': {
                        'currency': 'inr',
                        'unit_amount': int(obj.price * 100),
                        'product_data': {
                            'name': obj.product.name,
                        
                        },
                    },
                    'quantity': obj.quantity,
                },
            ],
       
            metadata={
                "product_id": obj.product_id
            },
            mode='payment',
            customer_email = current_user.email,
            
            success_url=YOUR_DOMAIN +'/success?session_id={CHECKOUT_SESSION_ID}',
            cancel_url=YOUR_DOMAIN + '/cancel',
    )
    
    order = Order()
    order.product_id = obj.product_id
    order.stripe_payment_intent = checkout_session['payment_intent']
    order.email=checkout_session['customer_email']
    order.price = int(checkout_session['amount_total']/100)
    order.quantity = obj.quantity
    order.userid = current_user.id
    order.status = 'Cancel'
    order.created_at = datetime.date.today()
    order.address_id = addressId
    order.save()
    return JsonResponse({
            'id': checkout_session.id
        })

def success(request):
    session_id = request.GET.get('session_id')
    if session_id is None:
       return HttpResponseNotFound()
    else:
        session = stripe.checkout.Session.retrieve(session_id)
        current_user = request.user
        list=User.objects.filter(id=current_user.id).values()
        obj= Order.objects.filter(stripe_payment_intent=session.payment_intent).update(status="success", has_paid=True)
        orders=Order.objects.filter(userid=current_user.id)
        current_user = request.user
        Cart.objects.filter(userid=current_user.id).delete()
        # send_mail(
        #     subject="Shoppers",
        #     message="your order has been confirmed",
        #     from_email=settings.EMAIL_HOST_USER,
        #     recipient_list=[current_user.email],
        #     fail_silently=False
        # )
        return render(request,"success.html",{'orders':orders[0],'list':list})

def order(request):
    if request.user.is_authenticated:
        current_user = request.user
        dataset= Order.objects.filter(userid=current_user.id).order_by('-created_at')
        return render(request, "order.html",{'dataset':dataset})
    else:
        return redirect("login")

def updateProfile(request):
    if request.user.is_authenticated:
        if request.method=="POST":
            obj=MyUserChangeForm(request.POST,instance=request.user)
            current_user=request.user
            email=request.POST['email']
            if User.objects.filter(email=email).exclude(id=current_user.id).exists():
                messages.info(request,"Email Already exists")
            elif obj.is_valid():
              obj.save()
              messages.success(request,"Account Updated Successfully")
              return redirect("updateProfile")
        else:
            obj=MyUserChangeForm(instance=request.user)
            current_user=request.user
        dataset= Address.objects.filter(user_id=current_user.id)
        return render(request,"account.html",{'obj':obj,'dataset':dataset})
    else:
        return redirect("login")

def updateAddress(request,id):
    if request.method=="POST":
        obj=Address.objects.get(id=id)
        form=AddressForm(request.POST,instance=obj)
        if form.is_valid():
            form.save()
            messages.success(request, f'Address Updated Successfully')
            return redirect("updateProfile")
    else:
        obj=Address.objects.get(id=id)
        form=AddressForm(instance=obj)
    return render(request,"project/update.html",{'form':form})

def delete_address(request,id):
    obj=Address.objects.filter(id=id)
    obj.delete()
    messages.success(request, f'Record Deleted Successfully')
    return redirect("updateProfile")














# def updateProfile(request):
#     form = MyUserChangeForm(request.POST, instance=request.user)

shop/project/templates/account.html
{% extends "base.html" %}
{% block content %}

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <form method="POST" action="">
    {% csrf_token %}
    {%for data in obj%}
    {{data.label_tag}} {{data}} {{data.errors|striptags}}<br><br>
    {%endfor%}
    <input type="submit" value="submit" name="submit" class="btn btn-info">
  </form>

  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
  <div class="tab-pane" id="billing">
    <div class="form-group">
      {%for a in dataset%}
      <address class="vcard">
        <span class="fn org">{{a.first_name}}</span>
        <span>{{a.last_name}}</span><br>
        <span>{{a.address}}</span><br>
        <span>{{a.city}}</span>
        <span>{{a.pincode}}</span><br>
        <span>{{a.mobile_no}}</span>
        <a button href="{%url 'updateAddress' a.id %}" class="btn" type="button"> Edit </a>
        <a button class="cart_quantity_delete" href="{%url 'delete_address' a.id %}" data-id="{{a.id}}" type="button">Delete</a> 
      </address>
      {%endfor%}
      <a href="/add_address" button class="btn btn-info" type="button">Add Address</a>
    </div>
  </div>
</body>

{%endblock%}

shop/project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

  <title>Shoppers &mdash; e-Commerce Template</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="{% static 'https://fonts.googleapis.com/css?family=Mukta:300,400,700' %}">
  <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css'%}">


  <link rel="stylesheet" href="{% static 'css/aos.css' %}">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

</head>

<body>

  <div class="site-wrap">
    <header class="site-navbar" role="banner">
      <div class="site-navbar-top">
        <div class="container">
          <div class="row align-items-center">

            <div class="col-6 col-md-4 order-2 order-md-1 site-search-icon text-left">
              <form action="" class="site-block-top-search">
                <span class="icon icon-search2"></span>
                <input type="text" class="form-control border-0" placeholder="Search">
              </form>
            </div>

            <div class="col-12 mb-3 mb-md-0 col-md-4 order-1 order-md-2 text-center">
              <div class="site-logo">
                <a href="/" class="js-logo-clone">Shoppers</a>
              </div>
            </div>

            <div class="col-6 col-md-4 order-3 order-md-3 text-right">
              <div class="site-top-icons">
                <ul>
                  <li><a href="#"><span class="icon icon-person"></span></a></li>
                  <li><a href="#"><span class="icon icon-heart-o"></span></a></li>
                  <li>

                    <a href="/cartdata" class="site-cart">
                      <span class="icon icon-shopping_cart"></span>
                      <span class="count">{{cart_record}}</span>
                    </a>


                  </li>
                  <li class="d-inline-block d-md-none ml-md-0"><a href="#" class="site-menu-toggle js-menu-toggle"><span
                        class="icon-menu"></span></a></li>
                </ul>
              </div>
            </div>

          </div>
        </div>
      </div>
      <nav class="site-navigation text-right text-md-center" role="navigation">
        <div class="container">
          <ul class="site-menu js-clone-nav d-none d-md-block">

            <li> <a href="/">Home</a></li>
            <li><a href="/updateProfile">My Account</a></li>
            {% if user.is_authenticated %}
            <li><a href="/add_address">Add Address</a></li>
            <li><a href="/passwordchange">Password Change</a></li>
            <li><a href="/order">My orders</a></li>
            <li><a href="/logout">Logout</a></li>
            {%else%}

            <li><a href="/login">Login</a></li>
            <li><a href="/createuser">Signup</a></li>
            {%endif%}

          </ul>
        </div>
      </nav>
    </header>

    {% block content %}{% endblock %}
    <footer class="site-footer border-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 mb-5 mb-lg-0">
            <div class="row">
              <div class="col-md-12">
                <h3 class="footer-heading mb-4">Navigations</h3>
              </div>
              <div class="col-md-6 col-lg-4">
                <ul class="list-unstyled">
                  <li><a href="#">Sell online</a></li>
                  <li><a href="#">Features</a></li>
                  <li><a href="#">Shopping cart</a></li>
                  <li><a href="#">Store builder</a></li>
                </ul>
              </div>
              <div class="col-md-6 col-lg-4">
                <ul class="list-unstyled">
                  <li><a href="#">Mobile commerce</a></li>
                  <li><a href="#">Dropshipping</a></li>
                  <li><a href="#">Website development</a></li>
                </ul>
              </div>
              <div class="col-md-6 col-lg-4">
                <ul class="list-unstyled">
                  <li><a href="#">Point of sale</a></li>
                  <li><a href="#">Hardware</a></li>
                  <li><a href="#">Software</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
            <h3 class="footer-heading mb-4">Promo</h3>
            <a href="#" class="block-6">
              <img src="{% static 'images/hero_1.jpg' %}" alt="Image placeholder" class="img-fluid rounded mb-4">
              <h3 class="font-weight-light  mb-0">Finding Your Perfect Shoes</h3>
              <p>Promo from nuary 15 &mdash; 25, 2019</p>
            </a>
          </div>
          <div class="col-md-6 col-lg-3">
            <div class="block-5 mb-5">
              <h3 class="footer-heading mb-4">Contact Info</h3>
              <ul class="list-unstyled">
                <li class="address">203 Fake St. Mountain View, San Francisco, California, USA</li>
                <li class="phone"><a href="tel://23923929210">+2 392 3929 210</a></li>
                <li class="email">emailaddress@domain.com</li>
              </ul>
            </div>

            <div class="block-7">
              <form action="#" method="post">
                <label for="email_subscribe" class="footer-heading">Subscribe</label>
                <div class="form-group">
                  <input type="text" class="form-control py-4" id="email_subscribe" placeholder="Email">
                  <input type="submit" class="btn btn-sm btn-primary" value="Send">
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <p>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              Copyright &copy;
              <script data-cfasync="false"
                src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
              <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made
              with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank"
                class="text-primary">Colorlib</a>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
          </div>

        </div>
      </div>
    </footer>
  </div>

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js'%}"></script>

  <script src="{% static 'js/main.js' %}"></script>
  <script src="https://js.stripe.com/v3/"></script>
</body>

</html

shop/project/templates/checkout.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load filters %}

<section id="cart_items">
    <div class="container">
        <div class="breadcrumbs">
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Check out</li>
            </ol>
        </div>
        <!--/breadcrums-->


        <div class="shopper-informations">
            <div class="row">
                <div class="col-sm-20">
                    <h1>Select Address</h1>
                    {%for a in showAddress%}
                    <address class="vcard">
                        <input addressId={{a.id}} type="radio" value={{a}} id="radio" name="radio">
                        <span>{{a.first_name}}</span>
                        <span>{{a.last_name}}</span><br>
                        <span>{{a.address}}</span><br>
                        <span>{{a.city}}</span>
                        <span>{{a.pincode}}</span><br>
                        <span>{{a.mobile_no}}</span>
                    
                        </span>
                    </address>
                    {%endfor%}
                    <a href="/add_address" button class="btn btn-info" type="button">Add Address</a>
                </div>
                <div class="review-payment">

                </div>

                <div class="table-responsive cart_info">

                    <table class="table table-condensed">
                        <thead>
                            <tr class="cart_menu">
                                <td class="image">Item</td>
                                <td class="description">Name</td>
                                <td class="price">Price</td>
                                <td class="quantity">Quantity</td>
                                <td class="total">Total</td>
                                <td></td>
                            </tr>
                        </thead>
                        <tbody>
                            {%for obj in checkList%}
                            <tr>
                                <td class="cart_product">
                                    <a href=""><img src="media/{{ obj.product.image }}" alt=""></a>
                                </td>
                                <td class="cart_description">
                                    <h4><a href="">{{obj.product.name}}</a></h4>

                                </td>
                                <td class="cart_price">
                                    <p>{{obj.price}}</p>
                                </td>
                                <td class="cart_quantity">
                                    <p>{{obj.quantity}}</p>
                                </td>
                                <td class="cart_total">
                                    <p class="cart_total_price">{% multiply obj.quantity obj.price %}</p>
                                </td>

                            </tr>
                            {%endfor%}


                            <tr>
                                <td colspan="4">&nbsp;</td>
                                <td colspan="2">
                                    <table class="table table-condensed total-result">

                                        <tr>
                                            <td>Total</td>
                                            <td><span>{{grandtotal}}</span></td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="payment-options">
                    <a id="pay" class="btn btn-primary" href="">Pay</a>
                </div>
            </div>
</section>
{% block javascript %}
<script>
    $('#pay').on('click', function () {
        var addressId = $('#radio:checked').attr("addressId");
        console.log(addressId)
        event.preventDefault();

        if (addressId) {
            var stripe = Stripe("pk_test_51L2TV5SBnyV9WLBjpNLBtZFUKflkVw2nQtCgcql9VctRgLF914chbWCrxJnUvx0kSvlfTCh6GKQa9qF1t3PFED0V007917JBMz");

            $.ajax({
                type: 'GET',
                url: '{% url "checkoutSession" %}',
                data: {
                    addressId: addressId
                },
                success: function (session) {
                    if (session.id) {
                        stripe.redirectToCheckout({ sessionId: session.id }).then(function (result) {
                            console.log(result, "failed data==>>>>");
                        });
                    }
                }
            })
        }
        else {
            alert("Please choose address")
        }
    }) 
</script>
{%endblock%}
{%endblock%}

shop/project/templates/empty.html
{% extends "base.html" %}
{% block content %}
<h1>Your Basket is now empty </h1>
<a href="/">Shop Now</a>
{% endblock %}

shop/project/templates/login.html
{% extends "base.html" %}
{% block content %}
<body>
    <h2>New User Signup!</h2>
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
		<button type="submit" name="login" class="btn btn-default">Login</button>
        <a href="{% url 'password_reset'%}">Reset Password</a>
</form>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
</body>
{%endblock%}

shop/project/templates/password_reset_done.html
{% extends "base.html" %}

{% block title %}Email Sent{% endblock %}

{% block content %}
  <h1>Check your inbox.</h1>
  <p>We've emailed you instructions for setting your password. You should receive the email shortly!</p>
{% endblock %}

shop/project/templates/person_address.html
{% extends 'base.html' %}
{% block content %}
<h2>Add Address</h2>
<form method="post" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    <a href="{% url 'person_changelist' %}">Nevermind</a>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_country").change(function () {
        var url = $("#personForm").attr("data-cities-url");
        var countryId = $(this).val();

        $.ajax({
            url: url,
            data: {
                'country': countryId
            },
            success: function (data) {
                $("#id_city").html(data);
            }
        });

    });
</script>

{% endblock %}
© 2022